CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  nickname TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'player',
  score INTEGER NOT NULL DEFAULT 0,
  is_frozen BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS words (
  id SERIAL PRIMARY KEY,
  book INTEGER NOT NULL,
  unit INTEGER NOT NULL,
  english TEXT NOT NULL,
  chinese TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(book, unit, english, chinese)
);

CREATE TABLE IF NOT EXISTS player_saves (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  unlocked_level INTEGER NOT NULL DEFAULT 1,
  completed_levels TEXT NOT NULL DEFAULT '[]',
  attempts TEXT NOT NULL DEFAULT '[]',
  last_played_at TIMESTAMP
);
